version: '3'
services:
    app:
        build: .
        command: npm run watch
        volumes:
            - .:/usr/hotel-app
            - /user/hotel-app/node_modules
        ports:
            - '3008:3008'