version: '3'
services:
    app:
        build:
           context: .
           dockerfile: Dockerfile
        command: npm run watch
        volumes:
            - .:/usr/hotel-app
            - /usr/hotel-app/node_modules
        ports:
            - '3008:3008'
